version: '3.1'

services:

  db:
    image: mysql
    container_name: harmony-mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "8082:3306"
    environment:
      MYSQL_DATABASE: harmonydb
      MYSQL_USER: harmonyuser
      MYSQL_PASSWORD: harmonypass
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - db:/var/lib/mysql

  phpmyadmin:
    container_name: harmony-phpmyadmin
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    ports:
      - '8081:80'
    environment:
      MYSQL_ROOT_PASSWORD: password

volumes:
  db: